### ISSUE TITLE
Profile: Add Security tab

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/dots-frontend#35]
This card is dependent on #7 

**Acceptance Criteria**
GIVEN I am a logged in user

AND I click on my profile icon in the top-right corner

AND click Profile

THEN I should be directed to the profile page and see vertical tabs

AND on the `Password` tab I should see the following fields:
![image](https://user-images.githubusercontent.com/4407063/81993520-27554c00-9646-11ea-9e11-5121027919b7.png)

**Comment by sannleen** [comment]
Hi @andrewtpham and @lupyana the feature is implemented:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/16039248/84914042-d52f9c80-b0c3-11ea-8282-6ef2683e3d47.png">

However, please make the profile a link so that it is intuitive to the user that it is clickable
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16039248/84914357-2e97cb80-b0c4-11ea-8f95-0d4106756965.png">

**Comment by sannleen** [comment]
Implemented
